name: Terraform Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.3

      - name: Initiate Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate